name: chat_gpt_sdk
description: SDK wrapper for ChatGPT
version: 0.0.1+1
homepage: https://www.grappfruit.com
repository: https://github.com/grAPPfruit/chat_gpt_sdk

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  dio: ^4.0.6
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

flutter:
